# Generated by Django 5.1.7 on 2025-05-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='College of Computer Studies', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='BS Information Technology', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
