# Generated by Django 5.1.7 on 2025-05-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ssio_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssio_username', models.CharField(max_length=150, unique=True)),
                ('ssio_email', models.EmailField(max_length=254, unique=True)),
                ('ssio_fname', models.CharField(max_length=150)),
                ('ssio_lname', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('ssio_userpin', models.CharField(blank=True, max_length=128, null=True)),
                ('access_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TS_Users.role')),
            ],
        ),
    ]
